#!/bin/sh
apt-get update -y
apt install nginx -y
apt install jq -y
systemctl start nginx
systemctl enable nginx
VM_NAME="$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq '.compute.name' -r)"
ZONE="$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq '.compute.zone' -r)"
echo "<h1><center>Hello there, from ${VM_NAME} from AZ-${ZONE}</center></h1>" > /var/www/html/index.html